# Generated by Django 5.0.6 on 2024-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('room', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('bhk', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('furnished', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('room', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('bhk', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('furnished', models.CharField(choices=[('Yes', 'Furnished'), ('Semi', 'Semi Furnished'), ('No', 'Not Furnished')], max_length=11)),
                ('image', models.ImageField(blank=True, upload_to='rental_property_images/')),
            ],
        ),
    ]
